# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFKcT99m4VEWiJLskJc_SnZcy79tGltS
"""

!pip install transformers datasets torch scikit-learn pandas numpy matplotlib seaborn nlpaug

"""Projenin ihtiyaç duyduğu tüm Python kütüphaneleri yüklenir ve import edilir. SEED=42 ile sonuçların tekrarlanabilirliği sağlanır, GPU varsa otomatik olarak kullanılır."""

import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from transformers import RobertaTokenizer, RobertaModel
from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score, f1_score,
                             precision_score, recall_score,
                             confusion_matrix, classification_report)
from sklearn.preprocessing import LabelEncoder
import nlpaug.augmenter.word as naw
import warnings
warnings.filterwarnings("ignore")

# Reproducibility
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Kullanılan cihaz: {device}")

""" Kaggle API üzerinden Twitter US Airline (14.640 tweet) ve IMDb (50.000 film yorumu) veri setleri indirilir. Her iki veri setinden sadece metin ve etiket sütunları alınır."""

# Kaggle'dan indirme (Colab'da)
# Önce Kaggle API key'ini ayarla:
# Sol panel > Files > upload > kaggle.json

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d crowdflower/twitter-airline-sentiment
!unzip twitter-airline-sentiment.zip

df_airline = pd.read_csv("Tweets.csv")

# Sadece gerekli sütunları al
df_airline = df_airline[["text", "airline_sentiment"]].copy()
df_airline.columns = ["text", "label"]
df_airline = df_airline.dropna()

print("Airline veri seti boyutu:", df_airline.shape)
print(df_airline["label"].value_counts())

!kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
!unzip imdb-dataset-of-50k-movie-reviews.zip

df_imdb = pd.read_csv("IMDB Dataset.csv")
df_imdb.columns = ["text", "label"]
df_imdb = df_imdb.dropna()

print("IMDb veri seti boyutu:", df_imdb.shape)
print(df_imdb["label"].value_counts())

"""1.6 milyon tweet içeren Sentiment140 veri seti indirilir. Orijinal formatta 0 ve 4 olan etiketler doğrudan 0 (negatif) ve 1 (pozitif) sayısal değerlerine dönüştürülür. Gereksiz sütunlar alınmaz, sadece label ve text kullanılır."""

!kaggle datasets download -d kazanova/sentiment140
!unzip sentiment140.zip

df_s140 = pd.read_csv(
    "training.1600000.processed.noemoticon.csv",
    encoding="latin-1",
    header=None
)
df_s140 = df_s140[[0, 5]].copy()
df_s140.columns = ["label", "text"]
df_s140["label"] = df_s140["label"].map({0: 0, 4: 1})
df_s140 = df_s140[["text", "label"]].dropna()

# Makale ile aynı: dengeli 1.6M
print("Sentiment140 boyutu:", df_s140.shape)
print(df_s140["label"].value_counts())

"""Küçük harfe çevirme, URL/hashtag/@mention/özel karakter/rakam temizliği, stop-word eleme ve lemmatizasyon yapılır. Airline ve IMDb bu hücrede işlenir, Sentiment140 örnekleme sonrasında ayrıca işlenir."""

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    # 1. Küçük harf
    text = text.lower()
    # 2. URL kaldır
    text = re.sub(r"http\S+|www\S+", "", text)
    # 3. Mention ve hashtag kaldır
    text = re.sub(r"@\w+|#\w+", "", text)
    # 4. Özel karakter ve sayıları kaldır
    text = re.sub(r"[^a-z\s]", "", text)
    # 5. Fazla boşlukları temizle
    text = re.sub(r"\s+", " ", text).strip()
    # 6. Stop-words kaldır
    tokens = text.split()
    tokens = [w for w in tokens if w not in stop_words]
    # 7. Lemmatizasyon
    tokens = [lemmatizer.lemmatize(w) for w in tokens]
    return " ".join(tokens)

# Ön işlemeyi uygula
df_airline["text"] = df_airline["text"].apply(preprocess)
df_imdb["text"]    = df_imdb["text"].apply(preprocess)

print("✓ Airline ve IMDb ön işleme tamamlandı")
print("Örnek temizlenmiş metin (Airline):")
print(df_airline["text"].iloc[0])

"""Airline için string etiketler (negative/neutral/positive) LabelEncoder ile 0/1/2'ye dönüştürülür. IMDb için aynı işlem yapılır. Sentiment140 zaten sayısal olduğu için doğrudan atanır."""

# Airline: negative / neutral / positive → 0, 1, 2
le_airline = LabelEncoder()
df_airline["label_enc"] = le_airline.fit_transform(df_airline["label"])
print("Airline sınıfları:", le_airline.classes_)

# IMDb: negative / positive → 0, 1
le_imdb = LabelEncoder()
df_imdb["label_enc"] = le_imdb.fit_transform(df_imdb["label"])
print("IMDb sınıfları:", le_imdb.classes_)

# Sentiment140: negative / positive → 0, 1
df_s140["label_enc"] = df_s140["label"]  # zaten 0/1
print("S140 sınıfları:", df_s140["label"].unique())

"""Üç veri setinin sınıf dağılımı yan yana bar grafik olarak gösterilir."""

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

for ax, df, title in zip(
    axes,
    [df_airline, df_imdb, df_s140],
    ["Twitter US Airline", "IMDb", "Sentiment140"]
):
    counts = df["label"].value_counts()
    ax.bar(counts.index, counts.values,
           color=["#e74c3c", "#3498db", "#2ecc71"][:len(counts)])
    ax.set_title(title)
    ax.set_xlabel("Sınıf")
    ax.set_ylabel("Örnek Sayısı")
    for i, v in enumerate(counts.values):
        ax.text(i, v + 50, str(v), ha="center", fontweight="bold")

plt.tight_layout()
plt.savefig("data_distribution.png", dpi=150)
plt.show()

""" Sadece Twitter Airline için augmentation yapılır çünkü bu tek dengesiz veri setidir. WordNet eş anlamlı kelime değiştirme yöntemiyle neutral ve positive sınıfları, negative sınıfının sayısına eşitlenir."""

def augment_class(df, label, target_count, aug):
    """Belirtilen sınıfı hedef sayıya kadar artır."""
    subset = df[df["label"] == label].copy()
    current = len(subset)
    needed  = target_count - current
    if needed <= 0:
        return subset

    texts = subset["text"].tolist()
    augmented_texts = []

    print(f"'{label}' için {needed} örnek üretiliyor...")
    while len(augmented_texts) < needed:
        batch = texts[:min(100, needed - len(augmented_texts))]
        try:
            result = aug.augment(batch)
            augmented_texts.extend(result)
        except:
            augmented_texts.extend(batch)  # hata olursa orijinali ekle

    aug_df = pd.DataFrame({
        "text": augmented_texts[:needed],
        "label": label,
        "label_enc": df[df["label"] == label]["label_enc"].iloc[0]
    })
    return pd.concat([subset, aug_df], ignore_index=True)

# Synonym augmentation
aug = naw.SynonymAug(aug_src="wordnet")

# Hedef: negatif sınıf sayısı kadar
target = df_airline["label"].value_counts()["negative"]
print(f"Hedef örnek sayısı (her sınıf): {target}")

df_neg  = df_airline[df_airline["label"] == "negative"].copy()
df_neu  = augment_class(df_airline, "neutral",  target, aug)
df_pos  = augment_class(df_airline, "positive", target, aug)

df_airline_aug = pd.concat([df_neg, df_neu, df_pos], ignore_index=True)
df_airline_aug = df_airline_aug.sample(frac=1, random_state=SEED).reset_index(drop=True)

print("\nAugmentation sonrası dağılım:")
print(df_airline_aug["label"].value_counts())

"""1.6 milyon tweet'ten dengeli olarak 200.000 örnek alınır — 100.000 pozitif, 100.000 negatif. Sadece bu örneklere ön işleme uygulanır. İlk 5 satır gösterilir."""

# ============================================================
# HÜCRE: Sentiment140 — Mevcut Dosyadan 200K Dengeli Örnek
# ============================================================
# Makale Bölüm V: "1.6 million tweets, Stanford University 2009"
# "equal distribution: positive 50%, negative 50%"
# Tam veri seti yerine 200K dengeli örnek kullanıyoruz
# (A100'de ~15 dk vs tam veri seti ~3-4 saat)

SENTIMENT140_SAMPLE = 200_000   # None yaparsanız tüm 1.6M kullanılır

cols_s140 = ["target","ids","date","flag","user","text"]
df_s140_raw = pd.read_csv(
    "training.1600000.processed.noemoticon.csv",
    encoding="latin-1",
    names=cols_s140, header=None, low_memory=False
)

# target: 0=negatif, 4=pozitif → doğrudan 0/1'e çevir
df_s140_raw["label"] = df_s140_raw["target"].map({0: 0, 4: 1})
df_s140_raw = df_s140_raw[["text","label"]].dropna()

print(f"Ham veri seti: {len(df_s140_raw):,} tweet")
print(df_s140_raw["label"].value_counts())

# Dengeli örnekleme: her sınıftan eşit sayıda al
if SENTIMENT140_SAMPLE is not None:
    half = SENTIMENT140_SAMPLE // 2
    pos  = df_s140_raw[df_s140_raw["label"] == 1].sample(half, random_state=SEED)
    neg  = df_s140_raw[df_s140_raw["label"] == 0].sample(half, random_state=SEED)
    df_s140 = pd.concat([pos, neg]).sample(frac=1, random_state=SEED).reset_index(drop=True)
    print(f"\n✓ {SENTIMENT140_SAMPLE:,} dengeli örnek alındı ({half:,} pos + {half:,} neg)")
else:
    df_s140 = df_s140_raw.sample(frac=1, random_state=SEED).reset_index(drop=True)
    print(f"\n✓ Tüm veri seti kullanılıyor: {len(df_s140):,} tweet")

# Ön işleme uygula (Algoritma 1, Adım 3-15)
print("\nÖn işleme uygulanıyor (bu birkaç dakika sürebilir)...")
df_s140["text"] = df_s140["text"].apply(preprocess)
df_s140 = df_s140[df_s140["text"].str.strip() != ""].reset_index(drop=True)

# label_enc: zaten 0/1, doğrudan kullan
df_s140["label_enc"] = df_s140["label"]
print(f"Sentiment140 sınıfları: {sorted(df_s140['label'].unique())}")
print(f"✓ Tamamlandı: {len(df_s140):,} temiz tweet")
print(df_s140["label"].value_counts())

# İlk 5 satırı göster — sadece target ve text sütunları
df_s140_raw[["label", "text"]].head()

"""200K örneklenmiş Sentiment140'ın sınıf dağılımı gösterilir."""

# ============================================================
# HÜCRE: Sentiment140 Dağılım Grafiği (Makale Şekil 2c)
# ============================================================
fig, ax = plt.subplots(figsize=(5, 4))
counts = df_s140["label"].value_counts()
bars = ax.bar(counts.index, counts.values,
              color=["#e74c3c","#3498db"], width=0.4)
for b in bars:
    ax.text(b.get_x()+b.get_width()/2, b.get_height()+200,
            f"{b.get_height():,}", ha="center", fontweight="bold")
ax.set_title("Sentiment140 — Sınıf Dağılımı")
ax.set_xlabel("Sınıf"); ax.set_ylabel("Örnek Sayısı")
ax.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.savefig("dist_sentiment140.png", dpi=130)
plt.show()
print("✓ Grafik kaydedildi: dist_sentiment140.png")

"""Her veri seti makale Tablo I'e göre %90 eğitim, %5 doğrulama, %5 test olarak ayrılır. Stratified split ile sınıf oranları korunur. Airline için augmentation yapılmış veri seti kullanılır."""

# ============================================================
# HÜCRE: Veri Bölünmesi %90 / %5 / %5  (Makale Tablo I)
# "Training: 90%, Validation: 5%, Testing: 5%"
# ============================================================

def split_90_5_5(df, label_col="label_enc", name=""):
    """
    Makale Tablo I: Training 90%, Validation 5%, Test 5%
    stratify: sınıf oranları korunur
    """
    train, temp = train_test_split(
        df, test_size=0.10,
        random_state=SEED, stratify=df[label_col]
    )
    val, test = train_test_split(
        temp, test_size=0.50,
        random_state=SEED, stratify=temp[label_col]
    )
    train = train.reset_index(drop=True)
    val   = val.reset_index(drop=True)
    test  = test.reset_index(drop=True)
    print(f"{name}  →  Eğitim:{len(train):>7,}  Doğrulama:{len(val):>6,}  Test:{len(test):>6,}")
    return train, val, test


# Twitter Airline → augmentation yapılmış veri setini kullan
train_airline, val_airline, test_airline = split_90_5_5(
    df_airline_aug, name="Twitter Airline (aug)")

# IMDb → orijinal dengeli veri seti
train_imdb, val_imdb, test_imdb = split_90_5_5(
    df_imdb, name="IMDb")

# Sentiment140 → 200K dengeli örnek
train_s140, val_s140, test_s140 = split_90_5_5(
    df_s140, name="Sentiment140")

print("\n✓ Veri bölünmesi tamamlandı")

""" RoBERTa tokenizer yüklenir. Her metin için input_id ve attention_mask üretilir. PyTorch DataLoader ile batch'ler oluşturulur."""

# ============================================================
# HÜCRE: PyTorch Dataset & DataLoader  (Makale Adım 16)
# "RoBERTa Tokenization: Input ID, Token ID, Attention Mask"
# ============================================================

MAX_LEN    = 128
BATCH_SIZE = 32

# RoBERTa tokenizer
print("RoBERTa tokenizer yükleniyor...")
tokenizer = RobertaTokenizer.from_pretrained("roberta-base")
print(f"✓ Tokenizer hazır | Kelime dağarcığı: {tokenizer.vocab_size:,}")


class SentimentDataset(Dataset):
    """
    Makale Adım 16:
    Her token için → Input ID + Attention Mask atanır
    """
    def __init__(self, texts, labels, tokenizer, max_len):
        self.texts     = texts
        self.labels    = labels
        self.tokenizer = tokenizer
        self.max_len   = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            str(self.texts[idx]),
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        return {
            "input_ids":      enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "label": torch.tensor(self.labels[idx], dtype=torch.long),
        }


def make_loaders(train_df, val_df, test_df,
                 text_col="text", label_col="label_enc"):
    def mk(df, shuffle):
        return DataLoader(
            SentimentDataset(
                df[text_col].tolist(),
                df[label_col].tolist(),
                tokenizer, MAX_LEN
            ),
            batch_size=BATCH_SIZE,
            shuffle=shuffle,
            num_workers=2,
            pin_memory=True,
        )
    return mk(train_df, True), mk(val_df, False), mk(test_df, False)


# Her veri seti için loader oluştur
train_loader_a, val_loader_a, test_loader_a = make_loaders(
    train_airline, val_airline, test_airline)
train_loader_i, val_loader_i, test_loader_i = make_loaders(
    train_imdb, val_imdb, test_imdb)
train_loader_s, val_loader_s, test_loader_s = make_loaders(
    train_s140, val_s140, test_s140)

print("✓ DataLoader'lar hazır")
print(f"  Airline  — train batch sayısı: {len(train_loader_a)}")
print(f"  IMDb     — train batch sayısı: {len(train_loader_i)}")
print(f"  S140     — train batch sayısı: {len(train_loader_s)}")

"""Makalenin önerdiği hibrit model tanımlanır. RoBERTa encoder (12 katman, 768 gizli birim) → Dropout (0.1) → BiLSTM (h=256, çıktı=512) → Dense katman → Softmax."""

# ============================================================
# HÜCRE: RoBERTa-BiLSTM Model  (Makale Bölüm IV, Şekil 1)
# ============================================================
# Mimari akışı (Algoritma 1):
#   Adım 16: RoBERTa Tokenization
#   Adım 17: RoBERTa Encoder (12 katman, 768 gizli birim)
#   Adım 18: Dropout (d=0.1)
#   Adım 19: BiLSTM (h=256, bidirectional → çıktı=512)
#   Adım 20: Flatten (ortalama havuzlama)
#   Adım 21: Dense katman 1
#   Adım 22: Dense katman 2 + Softmax

HIDDEN_UNITS = 256    # h ∈ {128,256,512} → makale en iyi: 256
DROPOUT      = 0.1    # d = 0.1
EPOCHS       = 5      # epoch = 5
LEARNING_RATE= 1e-5   # l = 0.00001 (makale en iyi)
WEIGHT_DECAY = 1e-2


class RoBERTaBiLSTM(nn.Module):


    def __init__(self, num_classes, hidden_units=HIDDEN_UNITS, dropout=DROPOUT):
        super().__init__()

        # Adım 17: RoBERTa Encoder
        self.roberta = RobertaModel.from_pretrained("roberta-base")
        roberta_dim  = self.roberta.config.hidden_size  # 768

        # Adım 18: Dropout
        self.dropout = nn.Dropout(dropout)

        # Adım 19: BiLSTM
        # "hidden units (h) will be doubled (2×h) for BiLSTM"
        self.bilstm = nn.LSTM(
            input_size  = roberta_dim,
            hidden_size = hidden_units,
            num_layers  = 1,
            batch_first = True,
            bidirectional=True,    # ileri (→) + geri (←)
        )
        bilstm_out = hidden_units * 2   # 256×2 = 512

        # Adım 21: Dense katman 1
        self.fc1   = nn.Linear(bilstm_out, 128)
        self.relu  = nn.ReLU()
        self.drop2 = nn.Dropout(dropout)

        # Adım 22: Dense katman 2 / Sınıflandırma
        # Softmax → CrossEntropyLoss içinde uygulanır
        self.fc2 = nn.Linear(128, num_classes)

    def forward(self, input_ids, attention_mask):
        # 1) RoBERTa: (B, L) → (B, L, 768)
        rob_out = self.roberta(
            input_ids=input_ids,
            attention_mask=attention_mask
        )
        seq_out = rob_out.last_hidden_state   # (B, L, 768)

        # 2) Dropout
        seq_out = self.dropout(seq_out)       # (B, L, 768)

        # 3) BiLSTM: (B, L, 768) → (B, L, 512)
        lstm_out, _ = self.bilstm(seq_out)

        # 4) Flatten: ortalama havuzlama (B, L, 512) → (B, 512)
        pooled = lstm_out.mean(dim=1)

        # 5) Dense + ReLU
        out = self.relu(self.fc1(pooled))
        out = self.drop2(out)

        # 6) Sınıflandırma logits (B, num_classes)
        return self.fc2(out)


# Parametre sayısını göster
_m = RoBERTaBiLSTM(num_classes=2).to(device)
total  = sum(p.numel() for p in _m.parameters())
trainable = sum(p.numel() for p in _m.parameters() if p.requires_grad)
print(f"✓ Model oluşturuldu")
print(f"  Toplam parametre     : {total:,}")
print(f"  Eğitilebilir param.  : {trainable:,}")
del _m; torch.cuda.empty_cache()

"""Makale Denklem 9'daki Categorical Cross-Entropy kayıp fonksiyonu, AdamW optimizer, linear warmup schedule tanımlanır. Değerlendirme fonksiyonu ağırlıklı F1, kesinlik ve duyarlılık hesaplar (Denklem 10-13). Mixed precision ile hız artırılır."""

# ============================================================
# HÜCRE: Eğitim & Değerlendirme  (Makale Denklem 9-13)
# ============================================================
from transformers import get_linear_schedule_with_warmup
import time

def train_one_epoch(model, loader, optimizer, scheduler,
                    criterion, scaler):

    model.train()
    total_loss = correct = total = 0

    for batch in loader:
        inp  = batch["input_ids"].to(device)
        mask = batch["attention_mask"].to(device)
        lbl  = batch["label"].to(device)

        optimizer.zero_grad()
        with torch.cuda.amp.autocast():
            logits = model(inp, mask)
            loss   = criterion(logits, lbl)  # Denklem 9

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        scaler.step(optimizer)
        scaler.update()
        scheduler.step()

        total_loss += loss.item() * lbl.size(0)
        correct    += (logits.argmax(1) == lbl).sum().item()
        total      += lbl.size(0)

    return total_loss/total, correct/total


@torch.no_grad()
def evaluate(model, loader, criterion):

    model.eval()
    total_loss = correct = total = 0
    all_preds, all_labels = [], []

    for batch in loader:
        inp  = batch["input_ids"].to(device)
        mask = batch["attention_mask"].to(device)
        lbl  = batch["label"].to(device)

        with torch.cuda.amp.autocast():
            logits = model(inp, mask)
            loss   = criterion(logits, lbl)

        total_loss += loss.item() * lbl.size(0)
        preds       = logits.argmax(1)
        correct    += (preds == lbl).sum().item()
        total      += lbl.size(0)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(lbl.cpu().numpy())

    acc  = correct / total
    f1w  = f1_score(all_labels, all_preds, average="weighted", zero_division=0)
    pw   = precision_score(all_labels, all_preds, average="weighted", zero_division=0)
    rw   = recall_score(all_labels, all_preds, average="weighted", zero_division=0)
    return total_loss/total, acc, f1w, pw, rw, all_preds, all_labels


def full_train(model, train_loader, val_loader,
               num_epochs, dataset_name):
    """
    5 epoch AdamW + linear warmup schedule.
    Her epoch sonunda en iyi model (val F1'e göre) kaydedilir.
    """
    criterion = nn.CrossEntropyLoss()
    optimizer = AdamW(model.parameters(),
                      lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    total_steps  = len(train_loader) * num_epochs
    warmup_steps = int(0.1 * total_steps)
    scheduler = get_linear_schedule_with_warmup(
        optimizer, warmup_steps, total_steps)
    scaler = torch.cuda.amp.GradScaler()

    history   = {k: [] for k in
                 ["train_loss","val_loss","train_acc","val_acc",
                  "val_f1","val_pw","val_rw"]}
    best_f1   = 0.0
    save_path = f"best_{dataset_name}.pt"

    print(f"\n{'='*60}")
    print(f"  {dataset_name} Eğitimi")
    print(f"  Epochs:{num_epochs}  Batch:{BATCH_SIZE}  "
          f"LR:{LEARNING_RATE}  h:{HIDDEN_UNITS}")
    print(f"{'='*60}")

    for ep in range(1, num_epochs+1):
        t0 = time.time()
        tr_loss, tr_acc = train_one_epoch(
            model, train_loader, optimizer,
            scheduler, criterion, scaler)
        vl_loss, vl_acc, vl_f1, vl_pw, vl_rw, _, _ = evaluate(
            model, val_loader, criterion)
        elapsed = time.time() - t0

        for k, v in zip(history,
                        [tr_loss,vl_loss,tr_acc,vl_acc,vl_f1,vl_pw,vl_rw]):
            history[k].append(v)

        print(f"Epoch {ep}/{num_epochs} [{elapsed:.0f}s] "
              f"TrLoss:{tr_loss:.4f} TrAcc:{tr_acc*100:.2f}% | "
              f"VlLoss:{vl_loss:.4f} VlAcc:{vl_acc*100:.2f}% "
              f"F1w:{vl_f1*100:.2f}%")

        if vl_f1 > best_f1:
            best_f1 = vl_f1
            torch.save(model.state_dict(), save_path)
            print(f"  ✓ En iyi model kaydedildi (Val F1:{best_f1*100:.2f}%)")

    return history, save_path


print("✓ Eğitim fonksiyonları tanımlandı")

"""Önce orijinal dengesiz veri seti ile eğitim yapılır, sonra augmentation uygulanmış veri seti ile. İki sonuç karşılaştırılır."""

# ============================================================
# HÜCRE: Twitter US Airline — Eğitim
# Makale: 3 sınıf, augmentation uygulandı
# Beklenen: A≈80.74%, F1w≈80.73%
# ============================================================

# ── Augmentation ÖNCESİ ────────────────────────────────────
print("▶ Augmentation ÖNCESİ eğitim...")
train_a_orig, val_a_orig, test_a_orig = split_90_5_5(
    df_airline, name="Airline (orijinal)")
tr_lo_a0, vl_lo_a0, te_lo_a0 = make_loaders(
    train_a_orig, val_a_orig, test_a_orig)

model_a0 = RoBERTaBiLSTM(num_classes=3).to(device)
hist_a0, path_a0 = full_train(
    model_a0, tr_lo_a0, vl_lo_a0, EPOCHS, "Airline_before_aug")

model_a0.load_state_dict(torch.load(path_a0, map_location=device))
_, acc_a0, f1_a0, pw_a0, rw_a0, preds_a0, labels_a0 = evaluate(
    model_a0, te_lo_a0, nn.CrossEntropyLoss())
print(f"\nAug ÖNCESİ TEST → A:{acc_a0*100:.2f}%  F1w:{f1_a0*100:.2f}%  "
      f"Pw:{pw_a0*100:.2f}%  Rw:{rw_a0*100:.2f}%")
del model_a0; torch.cuda.empty_cache()

# ── Augmentation SONRASI ───────────────────────────────────
print("\n▶ Augmentation SONRASI eğitim...")
model_a1 = RoBERTaBiLSTM(num_classes=3).to(device)
hist_a1, path_a1 = full_train(
    model_a1, train_loader_a, val_loader_a, EPOCHS, "Airline_after_aug")

model_a1.load_state_dict(torch.load(path_a1, map_location=device))
_, acc_a1, f1_a1, pw_a1, rw_a1, preds_a1, labels_a1 = evaluate(
    model_a1, test_loader_a, nn.CrossEntropyLoss())
print(f"\nAug SONRASI TEST → A:{acc_a1*100:.2f}%  F1w:{f1_a1*100:.2f}%  "
      f"Pw:{pw_a1*100:.2f}%  Rw:{rw_a1*100:.2f}%")
del model_a1; torch.cuda.empty_cache()

# ── Augmentation karşılaştırması (Makale Şekil 11) ─────────
labels_fig = ["Pw", "Rw", "F1w", "A"]
before = [pw_a0*100, rw_a0*100, f1_a0*100, acc_a0*100]
after  = [pw_a1*100, rw_a1*100, f1_a1*100, acc_a1*100]

x = np.arange(len(labels_fig)); w = 0.35
fig, ax = plt.subplots(figsize=(7,5))
bars1 = ax.bar(x-w/2, before, w, label="Aug Öncesi", color="#3498db")
bars2 = ax.bar(x+w/2, after,  w, label="Aug Sonrası", color="#e74c3c")
for b in list(bars1)+list(bars2):
    ax.text(b.get_x()+b.get_width()/2, b.get_height()+0.3,
            f"{b.get_height():.2f}%", ha="center", va="bottom", fontsize=8)
ax.set_xticks(x); ax.set_xticklabels(labels_fig)
ax.set_ylim(60, 105); ax.set_ylabel("Skor (%)")
ax.set_title("Twitter Airline — Augmentation Öncesi vs Sonrası (Makale Şekil 11)")
ax.legend(); ax.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.savefig("augmentation_comparison.png", dpi=130)
plt.show()

"""IMDb için model eğitilir, test sonuçları ve classification report yazdırılır. Makale referans değerleriyle karşılaştırılır."""

# ============================================================
# HÜCRE: IMDb — Eğitim
# Makale: 2 sınıf, dengeli veri seti
# Beklenen: A≈92.36%, F1w≈92.35%
# ============================================================
model_imdb = RoBERTaBiLSTM(num_classes=2).to(device)
hist_imdb, path_imdb = full_train(
    model_imdb, train_loader_i, val_loader_i, EPOCHS, "IMDb")

model_imdb.load_state_dict(torch.load(path_imdb, map_location=device))
criterion = nn.CrossEntropyLoss()
_, acc_i, f1_i, pw_i, rw_i, preds_i, labels_i = evaluate(
    model_imdb, test_loader_i, criterion)

print(f"\n{'─'*50}")
print(f"  IMDb TEST SONUÇLARI")
print(f"{'─'*50}")
print(f"  Doğruluk  (A) : {acc_i*100:.2f}%   (Makale: 92.36%)")
print(f"  F1 Skoru (F1w): {f1_i*100:.2f}%   (Makale: 92.35%)")
print(f"  Kesinlik  (Pw): {pw_i*100:.2f}%   (Makale: 92.46%)")
print(f"  Duyarlılık(Rw): {rw_i*100:.2f}%   (Makale: 92.36%)")
print(f"\n{classification_report(labels_i, preds_i, target_names=['Negatif','Pozitif'])}")

del model_imdb; torch.cuda.empty_cache()

"""Sentiment140 için model eğitilir. 200K örnekle makaleye yakın sonuçlar hedeflenir."""

# ============================================================
# HÜCRE: Sentiment140 — Eğitim
# Makale: 2 sınıf, dengeli, 1.6M tweet (biz 200K kullanıyoruz)
# Beklenen: A≈82.25%, F1w≈82.25%
# ============================================================
model_s140 = RoBERTaBiLSTM(num_classes=2).to(device)
hist_s140, path_s140 = full_train(
    model_s140, train_loader_s, val_loader_s, EPOCHS, "Sentiment140")

model_s140.load_state_dict(torch.load(path_s140, map_location=device))
criterion = nn.CrossEntropyLoss()
_, acc_s, f1_s, pw_s, rw_s, preds_s, labels_s = evaluate(
    model_s140, test_loader_s, criterion)

print(f"\n{'─'*50}")
print(f"  Sentiment140 TEST SONUÇLARI")
print(f"{'─'*50}")
print(f"  Doğruluk  (A) : {acc_s*100:.2f}%   (Makale: 82.25%)")
print(f"  F1 Skoru (F1w): {f1_s*100:.2f}%   (Makale: 82.25%)")
print(f"  Kesinlik  (Pw): {pw_s*100:.2f}%   (Makale: 82.25%)")
print(f"  Duyarlılık(Rw): {rw_s*100:.2f}%   (Makale: 82.25%)")
print(f"\n{classification_report(labels_s, preds_s, target_names=['Negatif','Pozitif'])}")

del model_s140; torch.cuda.empty_cache()

"""Her veri seti için kayıp eğrisi ve doğruluk/F1 eğrisi çizilir. Karmaşıklık matrisleri oluşturulur."""

# ============================================================
# HÜCRE: Eğitim Grafikleri  (Makale Şekil 5, 6, 7)
# Her veri seti için kayıp + doğruluk/F1 eğrisi
# ============================================================

def plot_history(history, name):
    ep = range(1, len(history["train_loss"])+1)
    fig, axes = plt.subplots(1, 2, figsize=(13, 4))

    # Kayıp eğrisi
    axes[0].plot(ep, history["train_loss"], "b-o", label="Eğitim")
    axes[0].plot(ep, history["val_loss"],   "r-o", label="Doğrulama")
    axes[0].set_title(f"{name} — Kayıp"); axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Kayıp"); axes[0].legend(); axes[0].grid(alpha=0.3)

    # Doğruluk & F1
    axes[1].plot(ep, [a*100 for a in history["train_acc"]], "b-o", label="Eğitim Acc")
    axes[1].plot(ep, [a*100 for a in history["val_acc"]],   "r-o", label="Doğrulama Acc")
    axes[1].plot(ep, [f*100 for f in history["val_f1"]],    "g--s", label="Doğrulama F1w")
    axes[1].set_title(f"{name} — Doğruluk & F1"); axes[1].set_xlabel("Epoch")
    axes[1].set_ylim(0, 100); axes[1].legend(); axes[1].grid(alpha=0.3)

    plt.suptitle(f"RoBERTa-BiLSTM — {name}", fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.savefig(f"history_{name}.png", dpi=130); plt.show()


def plot_confusion(labels, preds, class_names, name):
    cm = confusion_matrix(labels, preds)
    fig, ax = plt.subplots(figsize=(len(class_names)*2, len(class_names)*2))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=class_names, yticklabels=class_names, ax=ax)
    ax.set_xlabel("Tahmin"); ax.set_ylabel("Gerçek")
    ax.set_title(f"Karmaşıklık Matrisi — {name}")
    plt.tight_layout()
    plt.savefig(f"cm_{name}.png", dpi=130); plt.show()


# Airline (aug sonrası)
plot_history(hist_a1, "Twitter_Airline_AugSonrasi")
plot_confusion(labels_a1, preds_a1, ["Negatif","Nötr","Pozitif"], "Twitter_Airline")

# IMDb
plot_history(hist_imdb, "IMDb")
plot_confusion(labels_i, preds_i, ["Negatif","Pozitif"], "IMDb")

# Sentiment140
plot_history(hist_s140, "Sentiment140")
plot_confusion(labels_s, preds_s, ["Negatif","Pozitif"], "Sentiment140")

"""Her model kendi eğitim bağlamına uygun örneklerle test edilir. Airline modeli uçuş yorumlarını, IMDb filmleri, Sentiment140 genel tweetleri değerlendirir."""

# ============================================================
# HÜCRE: Demo — 3 Eğitilmiş Modelle Dışarıdan Örnek Tahmini
# ============================================================

def predict_single(text, model_path, num_classes, class_names_display):
    model = RoBERTaBiLSTM(num_classes=num_classes).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    cleaned = preprocess(text)

    enc = tokenizer(
        cleaned,
        max_length=MAX_LEN,
        padding="max_length",
        truncation=True,
        return_tensors="pt",
    )
    inp  = enc["input_ids"].to(device)
    mask = enc["attention_mask"].to(device)

    with torch.no_grad():
        with torch.cuda.amp.autocast():
            logits = model(inp, mask)
        probs    = torch.softmax(logits, dim=1).cpu().numpy()[0]
        pred_idx = probs.argmax()

    pred_label = class_names_display[pred_idx]

    print(f"  Ham metin    : {text}")
    print(f"  Temizlenmiş  : {cleaned if cleaned else '(boş)'}")
    print(f"  Tahmin       : ► {pred_label} ◄")
    print(f"  Olasılıklar  :")
    for i, (cn, p) in enumerate(zip(class_names_display, probs)):
        bar    = "█" * int(p * 30)
        marker = " ◀" if i == pred_idx else ""
        print(f"    {cn:<14}: {p*100:5.1f}%  {bar}{marker}")
    print()

    del model
    torch.cuda.empty_cache()
    return pred_label, probs


# ── Sabit sınıf isimleri (le_s140 artık kullanılmıyor) ───────
airline_display = ["Negatif ✗", "Nötr  ~", "Pozitif ✓"]  # 0,1,2
imdb_display    = ["Negatif ✗", "Pozitif ✓"]              # 0,1
s140_display    = ["Negatif ✗", "Pozitif ✓"]              # 0,1

# ── Örnek metinler ────────────────────────────────────────────
airline_ornekler = [
    "My flight was delayed 4 hours and nobody helped us. Terrible service!",
    "Amazing crew, smooth flight, will definitely book again with this airline!",
    "My flight departs from terminal B at 3pm, does anyone know the gate?",
    "The seat was uncomfortable but the food was surprisingly good.",
]

imdb_ornekler = [
    "This movie was a complete waste of time. Terrible acting and no plot whatsoever.",
    "One of the greatest films I have ever seen. A true masterpiece of cinema!",
    "Not perfect, but an enjoyable watch with some genuinely moving moments.",
    "Oh sure, the best movie of the year... if you enjoy watching paint dry.",
]

s140_ornekler = [
    "I hate Mondays so much, everything is going wrong today ugh",
    "Just got the best news ever!! So happy right now, life is beautiful :)",
    "Going to the store to buy some groceries, nothing special",
    "Great, my laptop crashed right before the deadline. Just great.",
]

# ── Airline modeli ────────────────────────────────────────────
print("\n" + "="*65)
print("  MODEL 1: Twitter US Airline  (3 sınıf: Negatif/Nötr/Pozitif)")
print("="*65)
for i, ornek in enumerate(airline_ornekler, 1):
    print(f"── Örnek {i} ──")
    predict_single(ornek, "best_Airline_after_aug.pt", 3, airline_display)

# ── IMDb modeli ───────────────────────────────────────────────
print("="*65)
print("  MODEL 2: IMDb Film Yorumları  (2 sınıf: Negatif/Pozitif)")
print("="*65)
for i, ornek in enumerate(imdb_ornekler, 1):
    print(f"── Örnek {i} ──")
    predict_single(ornek, "best_IMDb.pt", 2, imdb_display)

# ── Sentiment140 modeli ───────────────────────────────────────
print("="*65)
print("  MODEL 3: Sentiment140 Tweet Analizi  (2 sınıf: Negatif/Pozitif)")
print("="*65)
for i, ornek in enumerate(s140_ornekler, 1):
    print(f"── Örnek {i} ──")
    predict_single(ornek, "best_Sentiment140.pt", 2, s140_display)

print("✓ Demo tamamlandı!")

"""Aynı negatif cümle üç modele verilir, her modelin verdiği yanıt ve güven oranları karşılaştırılır."""

# ============================================================
# HÜCRE: Aynı Metin — 3 Model Karşılaştırması
# ============================================================

ortak_metin = "I can't believe how terrible this experience was, everything went wrong!"

print("="*65)
print(f"  Ortak metin: {ortak_metin}")
print("="*65)

print("\n── MODEL 1: Twitter Airline ──")
predict_single(ortak_metin, "best_Airline_after_aug.pt", 3, airline_display)

print("── MODEL 2: IMDb ──")
predict_single(ortak_metin, "best_IMDb.pt", 2, imdb_display)

print("── MODEL 3: Sentiment140 ──")
predict_single(ortak_metin, "best_Sentiment140.pt", 2, s140_display)